### ISSUE TITLE
Box width too small

### ISSUE THREAD

**Issue by kvigor** [harthur/rainbow#2]
WIN 7 x86
FF 5

When you click on the Rainbow Icon the width is so small the x to close it out is barely showing also when I click on the x the box don't close and or it sticks to the mouse.

**Comment by streetwolf** [comment]
Same here when using the Inspector.  To overcome this I use the following CSS code:

#rainbow-swatch {width :175px!important;  max-width :450px!important;}
#rainbow-swatch-colorval{margin-top: 0!important;}

**Comment by harthur** [comment]
This shouldn't be a problem anymore since the icons were removed in favor of auto-copying and closing the color box on click.

Re-open if needed.
