### ISSUE TITLE
How do I change foregrond colors

### ISSUE THREAD

**Issue by spiderplant0** [harthur/rainbow#6]
I can change the background color, but cant figure out how to change the color of text. Is this possible? Is there a link to step-by-step instructions.
Thanks

**Comment by harthur** [comment]
Yes, if you're using the colorpicker. Select an element. The font of the element should be displayed. Click on the text and you can change that color.

**Comment by Angels8** [comment]
i recently download a rainbow for Firefox and i don't know how to delete or undo a color can you help me please

**Comment by harthur** [comment]
@Angels8 you can't undo changing the color of an element. However, reloading the page will clear any of this.
