### ISSUE TITLE
Swedish locale files present, but locale not listed in chrome.manifest

### ISSUE THREAD

**Issue by Lakrits** [harthur/rainbow#7]
Hi,

I noticed when I had to re-download the Rainbow add-on off AMO after a computer overhaul, that Rainbow's Swedish locale (sv-SE) didn't load. After a check, I could see that the problem lies in the **chrome.manifest** file, which lacks an entry for the sv-SE locale. Everything else is in order, and the locale works perfectly when the chrome.manifest is mended.

Please fix that.

Best wishes,

Mikael Hiort af Ornäs

**Comment by harthur** [comment]
Wow, thanks for noticing. I apologize for missing this, and thanks for
translating the locale!

**Comment by harthur** [comment]
I uploaded a new version to AMO, hopefully it'll be approved soon.

**Comment by Lakrits** [comment]
Thanks :)

I always end up with my own test version after translating, so it took a while before I noticed.

Micke
