### ISSUE TITLE
Color not showing in library

### ISSUE THREAD

**Issue by Vip3re** [harthur/rainbow#8]
Hi, I love your addon, use it a lot.
But since I've installed the FT Deep Dark firefox Theme, I'm unable to see the color preview in the library. Do you think you can fix this or, at least, tell me if I could use some code with stylish to fix it myself?? I'd appreciate a lot, thanks.
![rainbow_bug](https://f.cloud.github.com/assets/5223050/955870/968ff23a-0432-11e3-9707-724357105069.JPG)

**Comment by harthur** [comment]
Thanks for reporting. Someone else has run into this issue without even any themes installed. I'll be looking into it today or tomorrow.

**Comment by harthur** [comment]
Firefox regression range: http://hg.mozilla.org/mozilla-central/pushloghtml?fromchange=86c98c4d36da&tochange=015da7030aab

Probably regressed by [bug 407956](https://bugzilla.mozilla.org/show_bug.cgi?id=407956)

**Comment by harthur** [comment]
This should be fixed by 72860ba.

New addon is up for review, give it a week for it to get reviewed and uploaded.
