### ISSUE TITLE
Context Menu Problem

### ISSUE THREAD

**Issue by streetwolf** [harthur/rainbow#9]
The only item I have on my Context Menu is 'Preview Element Color".  I recall that there were many more choices in the past.  I've been using the menu off of 'Tools' which has an entry called 'Rainbow' and cascades to six different entries.

I am running Fx26 Nightly but this started happening at least in Fx24 if I remember correctly.

**Comment by streetwolf** [comment]
Just to clarify I'm talking about the right-click context menu.

**Comment by harthur** [comment]
It's off by default, but you can turn it on by going to Rainbow > Settings > "Add to Context Menu"

**Comment by streetwolf** [comment]
Forgot to mention that it is on.  Always has been.

**Comment by streetwolf** [comment]
It is on.  Maybe you  changed what is on the context menu?  All I see is 'Preview Element Color.'  Turning the Context Menu setting off get's rid of this entry and vice versa.  Shouldn't the context menu have the same items on it that 'Tools' does?

**Comment by harthur** [comment]
My bad, you're right, that just toggles the Preview item.

There is a hacky way to get the menu back:

1) Enter `about:config` in the url bar
2) Click to accept "Void my warranty"
3) Search for the preference `extensions.rainbows.context`
4) Double click it to toggle it on

**Comment by streetwolf** [comment]
That did it. Thanks Heather.
